### ISSUE TITLE
Honor initSql and seedSql in ebean.test namespace ... into ebean.db.ddl

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test#33]
e.g.

```yaml
ebean:
    test:
        platform: postgres #, h2, postgres, mysql, oracle, sqlserver
        ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
        dbName: my_app
        initSql: init.sql
        seedSql: test.sql
```

Where test.sql and init.sql are files in `src/test/resources`.  

Note that initSql runs before create-all dll and seedSql runs after create-all ddl.
